name: Run Pull Request flow

on:
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: PWD
        run: pwd
      # - name: Danger
      #   run: /opt/homebrew/bin/danger-swift ci -d Dangerfile.swift
      - name: Danger
        uses: danger/swift@3.18.0
        with:
            args: --failOnErrors -dangerfile DangerFile.swift
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_RELEASE_BRANCH_PATTERN: "release/(transport|avia|bus|train)-"
